# Generated by Django 4.2 on 2023-04-24 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('finished_date', models.DateTimeField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('api_choice', models.CharField(blank=True, max_length=255, null=True)),
                ('email_result', models.BooleanField()),
                ('email', models.CharField(blank=True, max_length=255)),
                ('contextual_diff', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('error', models.TextField(blank=True)),
                ('error_stacktrace', models.TextField(blank=True)),
                ('zip_file', models.FileField(blank=True, null=True, upload_to='compare_results/')),
                ('zip_file_error', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_number', models.PositiveSmallIntegerField()),
                ('access_token', models.CharField(max_length=255)),
                ('instance_url', models.CharField(max_length=255)),
                ('org_id', models.CharField(max_length=255)),
                ('org_name', models.CharField(blank=True, max_length=255)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('error', models.TextField(blank=True)),
                ('error_stacktrace', models.TextField(blank=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compareorgs.job')),
            ],
        ),
        migrations.CreateModel(
            name='OfflineFileJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('error', models.TextField(blank=True, null=True)),
                ('error_stacktrace', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compareorgs.job')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compareorgs.org')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentListUnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diff_html', models.TextField(blank=True, null=True)),
                ('row_html', models.TextField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compareorgs.job')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('component_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compareorgs.componenttype')),
            ],
        ),
    ]
