# Generated by Django 6.0.1 on 2026-01-28 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compareorgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='random_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
